import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  site: 'https://defendabledocs.com',
  integrations: [
    starlight({
      title: 'DefendableDocs',
      tagline: 'The operating manual for DefendableOS and DefendableCloud. The engine that verifies. The vault that proves. To the shed.',
      description: 'The complete public documentation system for the DefendableOS + DefendableCloud ecosystem — the engine that verifies agentic work against a declared rulebook, and the hosted proof vault that mints hash-chained receipts.',
      logo: { src: './src/assets/logo.svg', replacesTitle: false },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/custom.css'],
      social: {
        github: 'https://github.com/SudoSuOps/defendable-docs',
      },
      editLink: {
        baseUrl: 'https://github.com/SudoSuOps/defendable-docs/edit/main/',
      },
      lastUpdated: true,
      pagination: true,
      defaultLocale: 'en',
      head: [
        { tag: 'meta', attrs: { property: 'og:type', content: 'website' } },
        { tag: 'meta', attrs: { property: 'og:site_name', content: 'DefendableDocs' } },
        { tag: 'meta', attrs: { name: 'theme-color', content: '#0a0a0a' } },
      ],
      sidebar: [
        {
          label: 'Field Release v0.1 (Audited Prototype)',
          collapsed: false,
          items: [
            { label: 'Field Proof Overview', link: '/field-release/overview/' },
            { label: 'Module Records', link: '/field-release/module-records/' },
            { label: 'Independent Audit / Receipt', link: '/field-release/audit-receipt/' },
            { label: 'Status Label System', link: '/field-release/status-labels/' },
          ],
        },
        {
          label: 'Start Here',
          items: [
            { label: 'Welcome', link: '/' },
            { label: 'Getting Started', link: '/getting-started/' },
          ],
        },
        {
          label: 'Ecosystem',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/ecosystem/overview/' },
            { label: 'Architecture', link: '/ecosystem/architecture/' },
            { label: 'Glossary', link: '/ecosystem/glossary/' },
            { label: 'Domain Map', link: '/ecosystem/domain-map/' },
            { label: 'Operating Principles', link: '/ecosystem/operating-principles/' },
          ],
        },
        {
          label: 'DefendableOS · the engine',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/defendableos/overview/' },
            { label: 'What It Is', link: '/defendableos/what-it-is/' },
            { label: 'What It Is NOT', link: '/defendableos/what-it-is-not/' },
            { label: 'Rulebook Engine', link: '/defendableos/rulebook-engine/' },
            { label: 'Why Now', link: '/defendableos/why-now/' },
            { label: 'Buyer Profile', link: '/defendableos/buyer-profile/' },
            { label: 'Use Cases', link: '/defendableos/use-cases/' },
            { label: 'Pricing Philosophy', link: '/defendableos/pricing-philosophy/' },
            { label: 'Board Flight Sheet (engagement)', link: '/defendableos/board-flight-sheet/' },
          ],
        },
        {
          label: 'DefendableCloud · the vault',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/defendablecloud/overview/' },
            { label: 'The Defendable Run', link: '/defendablecloud/the-defendable-run/' },
            { label: 'Three Lanes', link: '/defendablecloud/three-lanes/' },
            { label: 'Eval Lane · the referee', link: '/defendablecloud/eval-lane/' },
            { label: 'Generate a Receipt', link: '/defendablecloud/generate-a-receipt/' },
            { label: 'Integrate · dev quickstart', link: '/defendablecloud/integrate/' },
            { label: 'Defendable CLI', link: '/defendablecloud/cli/' },
            { label: 'API Reference', link: '/defendablecloud/api-reference/' },
          ],
        },
        {
          label: 'Mr. Defendable',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/mr-defendable/overview/' },
            { label: 'The Voice', link: '/mr-defendable/voice/' },
            { label: 'Proposal Flow', link: '/mr-defendable/proposal-flow/' },
            { label: 'Ring Ring Intake', link: '/mr-defendable/ring-ring-intake/' },
            { label: 'Board Room Language', link: '/mr-defendable/board-room-language/' },
            { label: 'To The Shed', link: '/mr-defendable/to-the-shed/' },
          ],
        },
        {
          label: 'Defend-A-Pedia',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/defend-a-pedia/overview/' },
            { label: 'Vocabulary as Infrastructure', link: '/defend-a-pedia/vocabulary-as-infrastructure/' },
            { label: 'Term Format', link: '/defend-a-pedia/term-format/' },
            { label: 'Schemas', link: '/defend-a-pedia/schemas/' },
            { label: 'Honey · Jelly · Propolis', link: '/defend-a-pedia/honey-jelly-propolis/' },
            { label: 'CRE → DefendableOS', link: '/defend-a-pedia/cre-to-defendableos/' },
            { label: 'Jr Broker Playbook', link: '/defend-a-pedia/jr-broker-playbook/' },
            { label: 'Sr Broker Playbook', link: '/defend-a-pedia/sr-broker-playbook/' },
          ],
        },
        {
          label: 'DefendableLedger',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/defendableledger/overview/' },
            { label: 'Four Rails', link: '/defendableledger/four-rails/' },
            { label: 'Royal Jelly Tiers', link: '/defendableledger/royal-jelly-tiers/' },
            { label: 'Hash-Chain Format', link: '/defendableledger/hash-chain/' },
            { label: 'Kill Hedera Doctrine', link: '/defendableledger/kill-hedera/' },
            { label: 'Publication Flow', link: '/defendableledger/publication-flow/' },
            { label: 'Verify a Record', link: '/defendableledger/verify/' },
            { label: 'Books and Records', link: '/defendableledger/books-and-records/' },
          ],
        },
        {
          label: 'StreetLedger (legacy)',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/streetledger/overview/' },
            { label: 'Deeded Vocabulary', link: '/streetledger/deeded-vocabulary/' },
            { label: 'Receipts', link: '/streetledger/receipts/' },
            { label: 'Manifests', link: '/streetledger/manifests/' },
            { label: 'SHA-256 Hashing', link: '/streetledger/sha256-hashing/' },
            { label: 'Object Storage Layout', link: '/streetledger/object-storage-layout/' },
            { label: 'Verify a Deed', link: '/streetledger/verify-a-deed/' },
            { label: 'Books and Records', link: '/streetledger/books-and-records/' },
          ],
        },
        {
          label: 'StreetChat',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/streetchat/overview/' },
            { label: 'Audio Ingestion', link: '/streetchat/audio-ingestion/' },
            { label: 'Whisper Transcription', link: '/streetchat/whisper-transcription/' },
            { label: 'Spaces Recording', link: '/streetchat/spaces-recording/' },
            { label: 'Street Pairs', link: '/streetchat/street-pairs/' },
            { label: 'Communicator Training', link: '/streetchat/communicator-training/' },
            { label: 'Object Storage Export', link: '/streetchat/object-storage-export/' },
            { label: 'Unknown Term Review', link: '/streetchat/unknown-term-review/' },
          ],
        },
        {
          label: 'DefendableRouter',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/defendablerouter/overview/' },
            { label: 'Routing Model', link: '/defendablerouter/routing-model/' },
            { label: 'ENS · App ID · Agent ID', link: '/defendablerouter/ens-app-agent-id/' },
            { label: 'Receipt Capture', link: '/defendablerouter/receipt-capture/' },
            { label: 'Edge Events', link: '/defendablerouter/edge-events/' },
            { label: 'API Contracts', link: '/defendablerouter/api-contracts/' },
            { label: 'Object Storage Flow', link: '/defendablerouter/object-storage-flow/' },
          ],
        },
        {
          label: 'Communicator',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/communicator/overview/' },
            { label: 'Human Meaning Layer', link: '/communicator/human-meaning-layer/' },
            { label: 'Street Talk → Directive', link: '/communicator/street-talk-to-directive/' },
            { label: 'Client Explanation', link: '/communicator/client-explanation/' },
            { label: 'Training Pairs', link: '/communicator/training-pairs/' },
            { label: 'Alignment Checks', link: '/communicator/alignment-checks/' },
          ],
        },
        {
          label: 'Tribunal · the referee',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/tribunal/overview/' },
            { label: 'Scoring Model', link: '/tribunal/scoring-model/' },
            { label: 'Validator Chain', link: '/tribunal/validator-chain/' },
            { label: 'Honey · Jelly · Propolis (severities)', link: '/tribunal/honey-royal-jelly-jelly-propolis/' },
            { label: 'Risk Tier (low/mid/high)', link: '/tribunal/risk-temperature/' },
            { label: 'Evidence Rules', link: '/tribunal/evidence-strength/' },
            { label: 'Assignment Success', link: '/tribunal/assignment-success/' },
            { label: 'Verdict JSON', link: '/tribunal/verdict-json/' },
          ],
        },
        {
          label: 'SwarmFixer',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/swarmfixer/overview/' },
            { label: 'Repair Intelligence', link: '/swarmfixer/repair-intelligence/' },
            { label: 'Failure → Fix Traces', link: '/swarmfixer/failure-to-fix-traces/' },
            { label: 'Repair Lift', link: '/swarmfixer/repair-lift/' },
            { label: 'Jelly Pipeline', link: '/swarmfixer/jelly-pipeline/' },
            { label: 'Training Data', link: '/swarmfixer/training-data/' },
            { label: 'Model Versions', link: '/swarmfixer/model-versions/' },
          ],
        },
        {
          label: 'DDEED',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/ddeed/overview/' },
            { label: 'Deed Schema', link: '/ddeed/deed-schema/' },
            { label: 'Receipt Schema', link: '/ddeed/receipt-schema/' },
            { label: 'Proof of Origin', link: '/ddeed/proof-of-origin/' },
            { label: 'Proof of Quality', link: '/ddeed/proof-of-quality/' },
            { label: 'Proof of Process', link: '/ddeed/proof-of-process/' },
            { label: 'Proof of Economics', link: '/ddeed/proof-of-economics/' },
            { label: 'Proof of Trust', link: '/ddeed/proof-of-trust/' },
          ],
        },
        {
          label: 'Cost to Mint',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/cost-to-mint/overview/' },
            { label: 'Compute Cost', link: '/cost-to-mint/compute-cost/' },
            { label: 'Validator Cost', link: '/cost-to-mint/validator-cost/' },
            { label: 'Storage Cost', link: '/cost-to-mint/storage-cost/' },
            { label: 'Energy', link: '/cost-to-mint/energy/' },
            { label: 'Per-Deed Economics', link: '/cost-to-mint/per-deed-economics/' },
            { label: 'Hyperscaler vs Edge', link: '/cost-to-mint/hyperscaler-vs-edge/' },
          ],
        },
        {
          label: 'Edge',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/edge/overview/' },
            { label: 'HoneyBox', link: '/edge/honeybox/' },
            { label: 'Defendable Box', link: '/edge/defendable-box/' },
            { label: 'GPU Fleet', link: '/edge/gpu-fleet/' },
            { label: 'Object Storage Sync', link: '/edge/object-storage-sync/' },
            { label: 'Offline Mode', link: '/edge/offline-mode/' },
            { label: 'Security', link: '/edge/security/' },
          ],
        },
        {
          label: 'AgentBench / ClawCheck',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/agentbench-clawcheck/overview/' },
            { label: 'Submit an Agent', link: '/agentbench-clawcheck/submit-agent/' },
            { label: 'Benchmark Pack', link: '/agentbench-clawcheck/benchmark-pack/' },
            { label: 'Failure Flags', link: '/agentbench-clawcheck/failure-flags/' },
            { label: 'Verdicts', link: '/agentbench-clawcheck/verdicts/' },
            { label: 'Reports', link: '/agentbench-clawcheck/reports/' },
          ],
        },
        {
          label: 'API',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/api/overview/' },
            { label: 'Authentication', link: '/api/authentication/' },
            { label: 'Receipts API', link: '/api/receipts-api/' },
            { label: 'Deeds API', link: '/api/deeds-api/' },
            { label: 'Tribunal API', link: '/api/tribunal-api/' },
            { label: 'Router API', link: '/api/router-api/' },
            { label: 'StreetLedger API', link: '/api/streetledger-api/' },
            { label: 'StreetChat API', link: '/api/streetchat-api/' },
            { label: 'Webhooks', link: '/api/webhooks/' },
          ],
        },
        {
          label: 'Schemas',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/schemas/overview/' },
            { label: 'Street Event', link: '/schemas/street-event/' },
            { label: 'Vocabulary Term', link: '/schemas/vocabulary-term/' },
            { label: 'Receipt', link: '/schemas/receipt/' },
            { label: 'Deed', link: '/schemas/deed/' },
            { label: 'Tribunal Verdict', link: '/schemas/tribunal-verdict/' },
            { label: 'Street Pair', link: '/schemas/street-pair/' },
            { label: 'Cost to Mint', link: '/schemas/cost-to-mint/' },
          ],
        },
        {
          label: 'Operations',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/operations/overview/' },
            { label: 'Deployment', link: '/operations/deployment/' },
            { label: 'Cloudflare Pages', link: '/operations/cloudflare-pages/' },
            { label: 'Object Storage', link: '/operations/object-storage/' },
            { label: 'Environment Variables', link: '/operations/environment-variables/' },
            { label: 'CI / CD', link: '/operations/ci-cd/' },
            { label: 'Monitoring', link: '/operations/monitoring/' },
            { label: 'Backup and Recovery', link: '/operations/backup-and-recovery/' },
          ],
        },
        {
          label: 'Examples',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/examples/overview/' },
            { label: 'Sample Receipt', link: '/examples/sample-receipt/' },
            { label: 'Sample Deed', link: '/examples/sample-deed/' },
            { label: 'Sample Tribunal Verdict', link: '/examples/sample-tribunal-verdict/' },
            { label: 'Sample Street Event', link: '/examples/sample-street-event/' },
            { label: 'Sample Street Pair', link: '/examples/sample-street-pair/' },
            { label: 'Sample Board Report', link: '/examples/sample-board-report/' },
            { label: 'Sample Flight Sheet', link: '/examples/sample-flight-sheet/' },
          ],
        },
        {
          label: 'Media',
          collapsed: true,
          items: [
            { label: 'Offense to the Shed', link: '/media/offense-to-the-shed/' },
            { label: 'Pain in the Shed', link: '/media/pain-in-the-shed/' },
            { label: 'Mr. Defendable Notes', link: '/media/mr-defendable-notes/' },
            { label: 'Content to Corpus', link: '/media/content-to-corpus/' },
          ],
        },
        {
          label: 'Legal & Risk',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/legal-risk/overview/' },
            { label: 'Privacy', link: '/legal-risk/privacy/' },
            { label: 'Consent for Recordings', link: '/legal-risk/consent-for-recordings/' },
            { label: 'Data Retention', link: '/legal-risk/data-retention/' },
            { label: '1031 Disclaimer', link: '/legal-risk/1031-disclaimer/' },
            { label: 'Not Legal / Tax Advice', link: '/legal-risk/not-legal-tax-advice/' },
          ],
        },
      ],
    }),
  ],
});
